# Generated by Django 5.2 on 2025-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
